import React from 'react'
import { Box, Typography } from "@mui/material";
import Banner from 'containers/LegalAgreement/Banner';

const PrivacyPolicy = () => {
  return (
    <Box
      width="100%"
      display="flex"
      justifyContent="center"
      alignItems="center"
      flexDirection="column"
    >
      <Banner
        title="Privacy Policy"
        description="An amazing set of templates allowing everyone to generate content 3x-5x faster"
      />
      <Box
        display="flex"
        flexDirection="column"
        sx={{ backgroundColor: "#FAFBFD" }}
        padding={2.5}

      >
        <Typography fontWeight={700} fontSize={17} mb={1}>
          Privacy Policy
        </Typography>
        <Typography color='#686363'>
          Information Collection and Use
          <br />
          We collect certain information when you use Reel Moment:
          <ul>
            <li>User Content: Content uploaded or generated by you while using the platform, such as videos, images, and text.</li>
            <li>Usage Data: Information about how you interact with our platform, including your device information, IP address, browser type, and access times.</li>
            <li>Cookies: We may use cookies to enhance your experience and gather additional usage data.</li>
          </ul>
          Use of Information
          <br />
          We use the collected information for various purposes:
          <ul>
            <li>To provide and maintain the Service.</li>
            <li>To personalize your experience and improve our platform.</li>
            <li>To communicate with you, including sending updates, notifications, and marketing materials.</li>
            <li>To analyze usage patterns and trends to enhance our services.</li>
          </ul>
          Information Sharing and Disclosure
          <br />
          Your information may be shared in the following circumstances:
          <ul>
            <li>Service Providers: We may engage third-party companies or individuals to facilitate our Service or assist in analyzing how our Service is used.
            </li>
            <li>Compliance with Laws: We may disclose your information if required by law or to protect our rights.
            </li>
          </ul>
          Data Security
          We prioritize the security of your information and implement appropriate measures to protect it. However, no method of transmission over the internet or electronic storage is entirely secure.
          Children's Privacy
          Reel Moment is not directed at individuals under the age of 13. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and become aware that your child has provided us with personal information, please contact us, and we will take steps to remove that information from our servers.
          Changes to This Privacy Policy
          We may update our Privacy Policy from time to time. Any changes will be posted on this page, and the updated policy will be effective when posted.
          Contact Us
          If you have any questions or concerns about our Privacy Policy or the handling of your information, please contact us at [contact email].
          <br />
          Last updated: [Dec 28,2023]
        </Typography>
      </Box>
    </Box>
  )
}

export default PrivacyPolicy